export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  UNAUTHORIZED_ERROR: "UNAUTHORIZED_ERROR",
  FORBIDDEN_ERROR: "FORBIDDEN_ERROR",
  BAD_REQUEST_ERROR: "BAD_REQUEST_ERROR",
  SIGNATURE_FAILURE: "SIGNATURE_FAILURE",
  RATE_LIMIT_ERROR: "RATE_LIMIT_ERROR",
  CONFLICT_ERROR: "CONFLICT_ERROR",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_ID: "INVALID_ID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
};
