const ORDER_STATUS = {
  CREATED: "CREATED",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
};

const SHIPPING_STATUS = {
  PENDING: "PENDING",
  PACKED: "PACKED",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
};

module.exports = { ORDER_STATUS, SHIPPING_STATUS, PAYMENT_STATUS };
